//! SVG 行扫描 + 拼装 lc DSL 字符串。
//!
//! 设计选择：不绑定 vtracer 内部 SvgPath/CompoundPath 类型（私有 API 易飘移），
//! 而是基于 vtracer 输出的 XML 文本做行级扫描。每个 `<path d="..." fill="..." .../>`
//! 独占一行，提取 d 与 fill 两段子串即可。

use crate::error::{Result, TraceError};

/// 把 vtracer 输出的 SVG 字符串转成 lc DSL。
///
/// `source` 是给生成注释使用的来源标签（一般是输入文件路径名）。
pub fn svg_to_lc(svg: &str, source: &str) -> Result<String> {
    let (width, height) = parse_svg_dimensions(svg)?;
    let paths = extract_paths(svg);

    let mut out = String::new();
    out.push_str(&format!(
        "// auto-generated by `lc trace` from {source} ({width}x{height}, {} paths)\n",
        paths.len()
    ));
    out.push_str("composition \"trace\" {\n");
    out.push_str(&format!("    width    = {width}\n"));
    out.push_str(&format!("    height   = {height}\n"));
    out.push_str("    fps      = 30\n");
    out.push_str("    duration = 1s\n\n");

    for (i, (d, fill)) in paths.iter().enumerate() {
        out.push_str(&format!("    shape path{i} {{\n"));
        out.push_str(&format!("        path     = \"{d}\"\n"));
        out.push_str(&format!("        fill     = {fill}\n"));
        out.push_str("        position = [0, 0]\n");
        out.push_str("    }\n");
    }
    out.push_str("}\n");
    Ok(out)
}

/// 从 `<svg ... width="W" height="H" ...>` 行中提取 W、H。
fn parse_svg_dimensions(svg: &str) -> Result<(u32, u32)> {
    let line = svg
        .lines()
        .find(|l| l.contains("<svg"))
        .ok_or_else(|| TraceError::VtracerFailed("vtracer 输出缺少 <svg> 标签".into()))?;
    let w = pick_attr(line, "width=\"")
        .and_then(|s| s.parse::<u32>().ok())
        .ok_or_else(|| TraceError::VtracerFailed("vtracer 输出缺少有效 width".into()))?;
    let h = pick_attr(line, "height=\"")
        .and_then(|s| s.parse::<u32>().ok())
        .ok_or_else(|| TraceError::VtracerFailed("vtracer 输出缺少有效 height".into()))?;
    Ok((w, h))
}

/// 抓出每条 `<path>` 的 (d, fill_hex)。无法解析的行被跳过（不算错）。
fn extract_paths(svg: &str) -> Vec<(String, String)> {
    svg.lines()
        .filter(|l| l.contains("<path "))
        .filter_map(scan_path_line)
        .collect()
}

/// 单行扫描：取 `d="..."` 和 `fill="..."`，把任意支持的 fill 格式归一为 `#RRGGBB`。
fn scan_path_line(line: &str) -> Option<(String, String)> {
    let d = pick_attr(line, "d=\"")?;
    let fill = pick_attr(line, "fill=\"")?;
    let hex = normalize_fill(&fill)?;
    Some((normalize_path_data(&d), hex))
}

/// 归一化 path data 以适配 lottiecode-lang Phase 1 的解析器：
/// 1. 逗号 → 空格（`M0,0 L80,0` → `M0 0 L80 0`）；
/// 2. 折叠多重空白；
/// 3. trim 首尾空白。
///
/// 注：lottiecode-lang Phase 1 仅支持 M/L/Z 命令。配合 `--mode polygon`
/// 即可让产物能直接被 `lc build` 编译。spline 模式输出含 C/Q 的 path
/// 字符串仍能写出，但需要等 Phase 2 才能 build。
fn normalize_path_data(d: &str) -> String {
    let replaced: String = d.chars().map(|c| if c == ',' { ' ' } else { c }).collect();
    replaced.split_whitespace().collect::<Vec<_>>().join(" ")
}

/// 在 `line` 中找 `key`（含等号与左引号），返回到下一个 `"` 之间的子串。
fn pick_attr(line: &str, key: &str) -> Option<String> {
    let start = line.find(key)? + key.len();
    let rest = &line[start..];
    let end = rest.find('"')?;
    Some(rest[..end].to_string())
}

/// 把 fill 属性值归一为大写 `#RRGGBB`。
///
/// vtracer 0.6.x 实际输出 `#rrggbb`（小写 hex），但历史版本和派生工具可能输出
/// `rgb(r,g,b)`。两种都接受，保证扫描器对输出格式漂移有容忍度。
fn normalize_fill(s: &str) -> Option<String> {
    let s = s.trim();
    if let Some(hex) = s.strip_prefix('#') {
        // 仅处理 6 位 hex；3 位简写、8 位带 alpha 暂不支持（vtracer 不输出）。
        if hex.len() != 6 || !hex.chars().all(|c| c.is_ascii_hexdigit()) {
            return None;
        }
        return Some(format!("#{}", hex.to_ascii_uppercase()));
    }
    let inner = s.strip_prefix("rgb(")?.strip_suffix(')')?;
    let parts: Vec<&str> = inner.split(',').map(|p| p.trim()).collect();
    if parts.len() != 3 {
        return None;
    }
    let r: u8 = parts[0].parse().ok()?;
    let g: u8 = parts[1].parse().ok()?;
    let b: u8 = parts[2].parse().ok()?;
    Some(format!("#{:02X}{:02X}{:02X}", r, g, b))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn normalize_path_data_replaces_commas_and_trims() {
        assert_eq!(
            normalize_path_data("M0,0 L80,0 L80,80 L0,80 Z "),
            "M0 0 L80 0 L80 80 L0 80 Z"
        );
        // 多重空白折叠。
        assert_eq!(normalize_path_data("M0  0   L1   1"), "M0 0 L1 1");
        // 已经合规的字符串原样保留（仅去尾空白）。
        assert_eq!(normalize_path_data("M0 0 L1 1 Z "), "M0 0 L1 1 Z");
    }

    #[test]
    fn scan_path_line_normalizes_comma_separated_d() {
        let line = r##"<path d="M0,0 L80,0 L80,80 L0,80 Z " fill="#ff0000"/>"##;
        let (d, hex) = scan_path_line(line).unwrap();
        assert_eq!(d, "M0 0 L80 0 L80 80 L0 80 Z");
        assert_eq!(hex, "#FF0000");
    }

    #[test]
    fn normalize_fill_accepts_hex_lowercase() {
        assert_eq!(normalize_fill("#fefefe").unwrap(), "#FEFEFE");
        assert_eq!(normalize_fill("#008000").unwrap(), "#008000");
        assert_eq!(normalize_fill("  #abcdef  ").unwrap(), "#ABCDEF");
    }

    #[test]
    fn normalize_fill_accepts_rgb() {
        assert_eq!(normalize_fill("rgb(15,255,0)").unwrap(), "#0FFF00");
        assert_eq!(normalize_fill("rgb(0, 0, 0)").unwrap(), "#000000");
        assert_eq!(normalize_fill("rgb(255, 255, 255)").unwrap(), "#FFFFFF");
    }

    #[test]
    fn normalize_fill_rejects_garbage() {
        assert!(normalize_fill("none").is_none());
        assert!(normalize_fill("#abc").is_none());        // 3 位简写不支持
        assert!(normalize_fill("#abcdefab").is_none());   // 8 位带 alpha 不支持
        assert!(normalize_fill("#xyzxyz").is_none());     // 非 hex 字符
        assert!(normalize_fill("rgb(1,2)").is_none());
        assert!(normalize_fill("rgb(a,b,c)").is_none());
    }

    #[test]
    fn scan_path_line_extracts_d_and_hex_fill() {
        let line = r##"<path d="M0 0 C26.4 0 Z" fill="#fefefe" transform="translate(0,0)"/>"##;
        let (d, hex) = scan_path_line(line).unwrap();
        assert_eq!(d, "M0 0 C26.4 0 Z");
        assert_eq!(hex, "#FEFEFE");
    }

    #[test]
    fn scan_path_line_extracts_d_and_rgb_fill() {
        let line = r#"<path d="M0 0 L1 1 Z" fill="rgb(10,20,30)" transform="translate(0.5,0.5)"/>"#;
        let (d, hex) = scan_path_line(line).unwrap();
        assert_eq!(d, "M0 0 L1 1 Z");
        assert_eq!(hex, "#0A141E");
    }

    #[test]
    fn extract_paths_skips_non_path_lines() {
        let svg = "\
<?xml version=\"1.0\" encoding=\"UTF-8\"?>
<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"100\" height=\"100\">
<path d=\"M0 0\" fill=\"#010203\"/>

<path d=\"M5 5\" fill=\"rgb(10,20,30)\"/>
</svg>";
        let paths = extract_paths(svg);
        assert_eq!(paths.len(), 2);
        assert_eq!(paths[0], ("M0 0".to_string(), "#010203".to_string()));
        assert_eq!(paths[1], ("M5 5".to_string(), "#0A141E".to_string()));
    }

    #[test]
    fn svg_to_lc_smoke() {
        // 仿真 vtracer 0.6.5 实际输出格式：fill 为小写 hex。
        let svg = "\
<svg xmlns=\"http://www.w3.org/2000/svg\" width=\"200\" height=\"150\">
<path d=\"M0 0 L10 0 L10 10 Z\" fill=\"#ff0000\" transform=\"translate(0,0)\"/>
<path d=\"M20 20 L30 20\" fill=\"#008000\" transform=\"translate(0,0)\"/>
</svg>";
        let lc = svg_to_lc(svg, "demo.png").unwrap();
        assert!(lc.contains("composition \"trace\""));
        assert!(lc.contains("width    = 200"));
        assert!(lc.contains("height   = 150"));
        assert!(lc.contains("shape path0"));
        assert!(lc.contains("shape path1"));
        assert!(lc.contains("fill     = #FF0000"));
        assert!(lc.contains("fill     = #008000"));
        assert!(lc.contains("position = [0, 0]"));
        assert!(lc.contains("(200x150, 2 paths)"));
    }

    #[test]
    fn svg_to_lc_handles_zero_paths() {
        let svg = "<svg width=\"10\" height=\"10\"></svg>";
        let lc = svg_to_lc(svg, "empty.png").unwrap();
        assert!(lc.contains("(10x10, 0 paths)"));
        assert!(lc.contains("composition"));
    }
}
