load("@rules_rust//rust:defs.bzl", "rust_library", "rust_test")

rust_library(
    name = "lottiecode-lang",
    srcs = glob(["src/**/*.rs"]),
    edition = "2021",
    visibility = ["//visibility:public"],
    deps = [
        "//crates/lottiecode-motion:lottiecode-motion",
        "@crates//:serde",
        "@crates//:serde_json",
    ],
)

rust_test(
    name = "lang_test",
    crate = ":lottiecode-lang",
)
